# Generated by Django 3.2.9 on 2021-12-03 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('mark', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='UsersCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.trainingcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "users' courses",
            },
        ),
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='school.trainingcourse')),
            ],
            options={
                'verbose_name_plural': 'text materials',
            },
        ),
        migrations.CreateModel(
            name='LinkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='school.trainingcourse')),
            ],
            options={
                'verbose_name_plural': 'Web-links',
            },
        ),
        migrations.CreateModel(
            name='FileMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='content/')),
                ('description', models.TextField()),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='school.trainingcourse')),
            ],
            options={
                'verbose_name_plural': 'file materials',
            },
        ),
    ]
