# Generated by Django 3.2.9 on 2021-12-03 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20211203_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
